notifications:
  email: false
sudo: required
matrix:
  include:
    - os: osx
      language: generic
      env:
        - MAC_PYTHON_VERSION=3.6.4
    - os: osx
      language: generic
      env:
        - MAC_PYTHON_VERSION=2.7.9
install:
- bash ./.travis/osx_install_python.sh $MAC_PYTHON_VERSION
- export PATH="/Library/Frameworks/Python.framework:$PATH"
- python --version
- which python
- which pip
- python -m pip 
- pip install -e .
- pip freeze
script:
- python setup.py test
- python setup.py bdist_wheel
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "dist/*.whl"
  skip_cleanup: true
  on:
    tags: true
