notifications:
  email: false
sudo: required
matrix:
  include:
    - os: osx
      language: generic
      env:
        - MAC_PYTHON_VERSION=3.6.4
    - os: osx
      language: generic
      env:
        - MAC_PYTHON_VERSION=2.7.9
install:
- source ./.travis/osx_install_python.sh $MAC_PYTHON_VERSION
-  ./.travis/.env/bin activate
- python --version
- pip --version
- which python
- which pip
- python -m pip --version
- python -m pip install -e .
- python -m pip freeze
script:
- python setup.py test
- python setup.py bdist_wheel
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "dist/*.whl"
  skip_cleanup: true
  on:
    tags: true
