notifications:
  email: false
sudo: required
matrix:
 include:
 - os: osx
   language: generic
   env: MAC_PYTHON_VERSION=2.7
 - os: osx
   language: generic
   env: MAC_PYTHON_VERSION=3.6
 - os: osx
   language: generic
   env: MAC_PYTHON_VERSION=3.7
 - os: linux
   language: python
   python: 3.6
before_install:
- source ./.travis/${TRAVIS_OS_NAME}_setup_python.sh $MAC_PYTHON_VERSION
install:
- python --version
- pip install -e .
- pip freeze
script:
- python setup.py test
before_deploy:
- bash ./.travis/${TRAVIS_OS_NAME}_build_wheel.sh
deploy:
  provider: releases
  api_key:
    secure: "jYWVac+94Xf1rAAt6VFiwSh5mEQegFijTXC/fHPJHA6zy6au+SUp5Zb3TIwbRb1RT+vyIfpYgUP/BDoC9a6Mdex656iBhO8diYQzmqOaqEZLX5Ms6UC1owpsSjM4oAmB+QL4ApeBZrCxBPQ8V+1pwCiN5R1FPMIYcnCzVE7y+Mbn3lNaWNQwtwuZSxXOdseLrG8AedSIo8ursAQ40XQ1esGxoxAvCWH5LT2bRhn94UxL/RHeU3m9jRxtMgps1eM0gYV2kiIqXPJVlUlhXMxNs0uzx1ImqatpRj1JGEEqnLZpkV+s3wnwvYklhQSBz5DqbTIMDPcmo+B0K37eArn6XV6VlFoMWtASIB1gVEjxX4ZmSdkUz6wL5bA/WkSHPbfImcV3NNV7/WyquFkjMNK/CzNEiL/RiDsGwmDvnd0ixLTD7M/fCA28SfmFmiGCWLUIgwY+jWb7NNCJsIAxO+DCkqDQvzasdSaZeeoliUxJ4yUjJY9K8W6b3wucfMPSotoLDArK5446AmsfwdmbQXHZUYfZNbxU6K8i0rpON2nm6IeA23TFTT8gtqCj6Wu3oiKv7IvZ3dD66oTn4tAHCa3iH3yHWenyRHnkUiIx3ft2/yiGYReEnwR9MirsnfsaGabKiuNFYvrdRrPHSAJCSBJhJuLZ/QesALqydDyJ3TmM8TE="
  file_glob: true
  file: "dist/*.whl"
  skip_cleanup: true
  on:
    tags: true
    os: osx
